// cards enum
const Card = {
    //spades
    "SA": "SA",
    "S2": "S2",
    "S3": "S3",
    "S4": "S4",
    "S5": "S5",
    "S6": "S6",
    "S7": "S7",
    "S8": "S8",
    "S9": "S9",
    "S10": "S10",
    "SJ": "SJ",
    "SQ": "SQ",
    "SK": "SK",
    //clubs
    "CA": "CA",
    "C2": "C2",
    "C3": "C3",
    "C4": "C4",
    "C5": "C5",
    "C6": "C6",
    "C7": "C7",
    "C8": "C8",
    "C9": "C9",
    "C10": "C10",
    "CJ": "CJ",
    "CQ": "CQ",
    "CK": "CK",
    //diamonds
    "DA": "DA",
    "D2": "D2",
    "D3": "D3",
    "D4": "D4",
    "D5": "D5",
    "D6": "D6",
    "D7": "D7",
    "D8": "D8",
    "D9": "D9",
    "D10": "D10",
    "DJ": "DJ",
    "DQ": "DQ",
    "DK": "DK",
    //hearts
    "HA": "HA",
    "H2": "H2",
    "H3": "H3",
    "H4": "H4",
    "H5": "H5",
    "H6": "H6",
    "H7": "H7",
    "H8": "H8",
    "H9": "H9",
    "H10": "H10",
    "HJ": "HJ",
    "HQ": "HQ",
    "HK": "HK", 
}

module.exports = Card